### PR TITLE
First Submition

### PR DESCRIPTION
**Pull request by michaelasong**
I have created a new branch for my capstone project
And sending for a new review

### CODE REVIEW

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @michaelasong 
### I'm Levy your PR reviewer.

Good job so far! :+1: 
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!




## Suggested changes
_Check the comments under the review._  
 
- [ ] Kindly make sure to deploy your website and remember to add the link in the Readme file.

- [ ] KIndly make to record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. Remember to add the video link to your pull request description. The content of the video should include:

    -  description of the project.
    -  A demo of the project features (different pages and different screen sizes).
     -  You should also highlight some interesting piece of code or something you built that you are very proud of.

- [ ] KIndly make sure to align correctly the content in order to stick to the provided design.:wink: Please do your best to use the correct typography like on the provided design.

    - ### Your design
  1. ### Home
mobile (4) 

image

    
   - ### Provided design
      [Behance design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)

  - [ ] Kindly make sure to provide the correct contents on the about page in order to meet the provided design.
    
     - ### Your design
 
  mobile (5)

- [ ] Kindly make sure that we can be able to review the mobile when we click on the hamburger icon. At this moment it is not clickable!

- [ ] Kindly make sure The README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by michaelasong** [comment]
hello, When do you mean I should align please could you be more specific?

**Review by MaganaAsiati — COMMENTED** [review]
# Hi @chuaindia 

made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :negative_squared_cross_mark:

- [ ] You have submitted a project, but the stylelint is not passing. Follow [this instruction](https://github.com/microverseinc/linters-config/tree/master/html-css#html--css3-course) to configure the linter properly. Make sure that you have installed node  js  to run npm and npx and check the autocorrect for linters
- [ ] Make  sure you submit a project without conflict between your branches, I see that you have a conflict In your branch solve it first before the next submission
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏




Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
Cheers and Happy coding!👏👏👏
--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by michaelasong** [comment]
hello

**Review by MaganaAsiati — APPROVED** [review]
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @michaelasong   , I'm @MaganaAsiati , your reviewer for this PR  :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


clap

## Highlights
- descriptive README file  :heavy_check_mark:👨🏻‍💻
- Your commits should start with a capital letter :heavy_check_mark:👨🏻‍💻


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] kindly  Add a descriptive description in your pull request in the future which give more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Cheers and Happy coding!👏👏👏

**Pull request merged**
